package eCommerce.dominio;

public enum ETipoLogradouro {
	ALAMEDA		,
	AVENIDA     ,
	BECO        ,
	BOULEVARD   ,
	CAMINHO     ,
	CAIS        ,
	CAMPO       ,
	ESCADA      ,
	ESTRADA     ,
	FAVELA      ,
	FAZENDA     ,
	FLORESTA    ,
	ILHA        ,
	JARDIM      ,
	LADEIRA     ,
	LARGO       ,
	LOTEAMENTO  ,
	LUGAR       ,
	MORRO       ,
	PARQUE      ,
	PASSEIO     ,
	PRAIA       ,
	PRAÇA       ,
	RECANTO     ,
	RODOVIA     ,
	RUA         ,
	SERVIDAO    ,
	TRAVESSA    ,
	VIA         ,
	VILA;
}
